export const fetchProblemsType = {
    FETCH_PROBLEMS: 'FETCH_PROBLEMS',
    FETCH_PROBLEMS_SUCCESS: 'FETCH_PROBLEMS_SUCCESS',
    FETCH_PROBLEMS_FAIL: 'FETCH_PROBLEMS_FAIL'
}

export const solveProblemsType = {
    FETCH_SOLVED: 'FETCH_SOLVED',
    FETCH_SOLVED_SUCCESS: 'FETCH_SOLVED_SUCCESS',
    MARK_SOLVED: 'MARK_SOLVED',
    MARK_UNSOLVED: 'MARK_UNSOLVED'
}

export const filterProblemsType = {
    UPDATE_FILTER: 'UPDATE_FILTER'
}